name: Vercel Staging Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main # It will trigger on staging branch
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main # This ensures the staging branch is used for the build
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Fix Git Author
        run: |
          git config user.name "Unmapt Bot"
          git config user.email "arge@rida-reports.co.uk"
          git commit --amend --no-edit --reset-author

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Rename Environment File
        run: mv .vercel/.env.production.local .env

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
